### ISSUE TITLE
Breakout channel persistence/restoration issues

### ISSUE THREAD

**Issue by plamoni** [GamesDoneQuick/gdq-break-channels#15]
I spotted the [Breakout channel](https://github.com/GamesDoneQuick/gdq-break-channels/tree/main/src/channels/breakout) twice on stream in the past 12 hours or so (once last night and once this morning).

There appears to be some sort of persistence/restoration issue with it.

Last night, when it first showed it played fine for a little bit before Super Mario Odyssey. There was a false start to the run and the stream kicked back to the break channel, at which point the paddle wasn't moving and I saw a ball bounce off a block without eliminating it.

This morning (in the break before Curse of Monkey Island), it seemed to be having the same issue. There was a ball stuck on the screen (just below the paddle, which was also stalled). New balls were getting created when donations came in, but because the paddle was stalled, they would just bounce into the de-spawn plane.

There appear to be two symptoms:

1. Balls not eliminating blocks
2. The paddle not tracking balls properly (i.e. stalling and not moving at all)

Ball spawning and collisions seem to be working as expected.

I haven't been able to reproduce the issue in the test application (running on MacOS 13.3.1 on an Intel Mac in Chrome 113.0.5672.126).

I'd love to get this fixed ASAP. Any guesses on where the problem might be coming from (e.g. differences between the main host application and the testbed app) would be appreciated.

Thanks and apologies for the issues.

**Comment by plamoni** [comment]
The two issues seem like they might actually be unrelated. What leads me to believe this is that the collision/block elimination is entirely [handled within the `Breakout` class](https://github.com/GamesDoneQuick/gdq-break-channels/blob/018655ba5de35d51c58f212a4f29e66c1645a57f/src/channels/breakout/game/breakout.ts#L113-L119), which gets persisted/restored [via a replicant](https://github.com/GamesDoneQuick/gdq-break-channels/blob/018655ba5de35d51c58f212a4f29e66c1645a57f/src/channels/breakout/hook.ts#L5-L35). Meanwhile the AI gets [regenerated each time the component loads](https://github.com/GamesDoneQuick/gdq-break-channels/blob/018655ba5de35d51c58f212a4f29e66c1645a57f/src/channels/breakout/index.tsx#L260-L273).

If the AI's [check process interval](https://github.com/GamesDoneQuick/gdq-break-channels/blob/018655ba5de35d51c58f212a4f29e66c1645a57f/src/channels/breakout/index.tsx#L265-L267) isn't running, that would explain why the paddle isn't moving, but wouldn't mess with block elimination.

Clearly the [Breakout tick loop](https://github.com/GamesDoneQuick/gdq-break-channels/blob/018655ba5de35d51c58f212a4f29e66c1645a57f/src/channels/breakout/game/breakout.ts#L42-L46) is running properly (because balls move around). Also, collision detection seems to be _generally_ working (because balls bounce off walls/blocks and get de-spawned properly when the hit the bottom of the screen).

Given this, I'm inclined to try refactoring the AI to work more like the Breakout class (though it's not stateful, so it doesn't make sense to persist it to a replicant ... maybe have it attach as part of the `useBreakout` hook?). This might get the AI to work properly, but it doesn't explain or potentially fix the block elimination issue.

**Comment by plamoni** [comment]
Obligatory "This has never happened before!" 😭😭😭

**Comment by plamoni** [comment]
@chrishanel or @VodBox --- Are there perhaps error logs produced by NodeCG? Any chance my channel is throwing exceptions? I'm starting to think that might explain the problems I'm seeing on the stream.

I'm experimenting with various bad data and also going to confirm I'm cleaning everything up right on channel changes/unloading.

**Comment by VodBox** [comment]
The first time that it broke, I did see an error show up in our logs for ``Mismatched revision number, assignment rejected`` which seems to suggest multiple assignments at the same time occurring out of order.

**Comment by plamoni** [comment]
> I did see an error show up in our logs for Mismatched revision number, assignment rejected which seems to suggest multiple assignments at the same time occurring out of order.

Is this a NodeCG error? Maybe something to do with my replicant usage? I followed the example from the Tetris channel where it serializes [after each turn](https://github.com/GamesDoneQuick/gdq-break-channels/blob/018655ba5de35d51c58f212a4f29e66c1645a57f/src/channels/tetris/hook.ts#L19) and [when unloaded](https://github.com/GamesDoneQuick/gdq-break-channels/blob/018655ba5de35d51c58f212a4f29e66c1645a57f/src/channels/tetris/hook.ts#LL25C1-L26C1). Though because Tetris turns happen relatively infrequently, I just [put mine in a `setInterval`](https://github.com/GamesDoneQuick/gdq-break-channels/blob/018655ba5de35d51c58f212a4f29e66c1645a57f/src/channels/breakout/hook.ts#L22) instead of saving after each turn. Honestly I feel like the unload is adequate (and I'm fine with it losing state when it's unloaded). So maybe one thing to try would be to remove the periodic save to the replicant?

Another thing I was considering was having the AI load when the replicant is loaded ([here](https://github.com/GamesDoneQuick/gdq-break-channels/blob/018655ba5de35d51c58f212a4f29e66c1645a57f/src/channels/breakout/hook.ts#L12-L15)). Because the game seems to be coming up fine, but the AI seems hosed.

That doesn't explain the stuck ball(s). But I'd feel better about having a stuck ball on the screen if the paddle still moved.

**Comment by VodBox** [comment]
That's a NodeCG error that occurs when the server rejects a change made by a browser page.

I intend to take a closer look at this myself here in a bit.

**Comment by plamoni** [comment]
> I intend to take a closer look at this myself here in a bit.

Thanks a bunch. I feel somewhat powerless to fix the problem without being able to reproduce it or take many of the other debugging steps I'd normally perform.

I've been watching GDQ twice a year for more than a decade. It's great to have an opportunity to make a contribution that's not just money. But super-frustrating to see it bonk each time it comes up.

**Comment by VodBox** [comment]
Fixed by https://github.com/GamesDoneQuick/gdq-break-channels/commit/644d35a6e7bf32d8757e5ffb2b994ea26ec7cb83

**Comment by plamoni** [comment]
Just to understand, it looks like I was mutating the object being sent to the replicant after sending it to NodeCG and that hosed things? And I couldn’t reproduce at home because the issue doesn’t get simulated by the NodeCG shim?

**Comment by VodBox** [comment]
It wasn't an issue that you were mutating objects after sending them to NodeCG: that kind of thing is safe to do.

The issue came from when deserializing the state from the replicant. The objects returned by the value on a Replicant are proxies, and any mutations on _those_ objects will be synced with the server, and since the breakout state manager was using those proxies directly, _then_ is when it would hose the server with changes that it would then reject. This is why things worked when the channel first appeared, but broke on subsequent appearances.

The shim behaves more like the server and accepts all changes as they come in, while changes sent from browser pages are managed with diffs to try to have eventual consistency and it rejects changes that don't appear to be consistent or appear out of sync, hence why this wasn't observed within the simulator.

**Comment by plamoni** [comment]
Ah, that makes sense. I was reading it on my phone earlier and missed that it was in the deserialization function. Thanks again.

**Comment by plamoni** [comment]
I’ve been watching to see if the fix worked but honestly haven’t seen it rotated in since the fix was merged. Was it pulled from the rotation since it was broken?

**Comment by VodBox** [comment]
Despite seemingly fixing it in testing, the event instance kept having issues when the channel switched, so it was pulled from rotation unfortunately. I will take a look at some point to see if there are still remaining issues or if it's just prior bad data in the replicants that needed to be cleared, but things should be good for future events like Flame Fatales and AGDQ.

**Comment by plamoni** [comment]
Sorry to hear. I understand. And I really appreciate the effort to help fix it. Hope to see it in the rotation at some point. And definitely let me know if there's anything I can do to help out. I had a great time making it and will contribute again if inspiration strikes.

Thanks for all y'all do!
