### ISSUE TITLE
Would a Fallout 2 themed channel be allowed?

### ISSUE THREAD

**Issue by ChrissiQ** [GamesDoneQuick/gdq-break-channels#43]
Hi there, I had a question and not sure where else to reach the people who might be able to answer it (I asked on Discord and they directed me to perhaps ask here?)

I've read the contributing guidelines and I'd like to work on a Fallout 2 channel, maybe a pip boy, but before I expend energy on it I just wanted to make sure it would not fall under "too recently developed or still commercially marketed"?  It's technically being sold on Steam and GoG but since it's 25 years old I was hoping it might be fine.

Thanks!

**Comment by VodBox** [comment]
Discussing it internally, we think we would be able to accept a Fallout 2 themed channel as long as it fits within our other guidelines.

Looking forward to hopefully seeing a submission in the near future! 😄
